import { lazy } from 'react';
import { UserRound } from 'lucide-react';
import type { AppModule } from '@/core/modules/types';

const ProfilePage = lazy(() => import('./pages/ProfilePage'));

export const profileModule: AppModule = {
  id: 'profile',
  version: '0.1.0',
  title: 'profile:title',
  icon: UserRound,
  emoji: '🌸',
  enabledByDefault: true,
  nav: { order: 90, placement: 'main' },
  routes: [{ index: true, element: <ProfilePage /> }],
  i18n: {
    uk: {
      title: 'Профіль',
      heading: 'Мій кабінет',
      displayName: 'Ім’я',
      bio: 'Про мене',
      avatar: 'Емодзі-аватар',
      timezone: 'Часовий пояс',
      rollover: 'Новий день починається о (година)',
      language: 'Мова',
      theme: 'Тема',
      themeLight: 'Світла',
      themeDark: 'Темна',
      themeSystem: 'Як у системі',
      goal: 'Денна ціль XP',
      save: 'Зберегти',
      saved: 'Збережено ✨',
      saveError: 'Не вдалося зберегти. Спробуй ще раз.',
      security: 'Безпека',
      signOut: 'Вийти',
      signOutAll: 'Вийти на всіх пристроях',
      photo: {
        label: 'Фото профілю',
        upload: 'Завантажити фото',
        remove: 'Прибрати фото',
        hint: 'PNG, JPG або WebP, до 2 МБ. Без фото буде емодзі-аватар.',
        badType: 'Підтримуються лише PNG, JPG та WebP.',
        tooBig: 'Файл завеликий. Максимум 2 МБ.',
        error: 'Не вдалося оновити фото. Спробуй ще раз.',
      },
      password: {
        heading: 'Змінити пароль',
        current: 'Поточний пароль',
        next: 'Новий пароль',
        confirm: 'Повтори новий пароль',
        hint: 'Щонайменше 10 символів.',
        submit: 'Змінити пароль',
        done: 'Пароль змінено ✨',
        tooShort: 'Пароль має містити щонайменше 10 символів.',
        same: 'Новий пароль має відрізнятися від поточного.',
        mismatch: 'Паролі не збігаються.',
        wrongCurrent: 'Поточний пароль невірний.',
        error: 'Не вдалося змінити пароль. Спробуй ще раз.',
      },
      mfa: {
        heading: 'Двофакторний захист',
        hint: 'Додатковий код із застосунку-автентифікатора під час входу.',
        enabled: 'Двофакторний захист увімкнено ✅',
        enable: 'Увімкнути',
        disable: 'Вимкнути',
        scan: 'Скануй QR-код у застосунку-автентифікаторі (Google Authenticator, Authy тощо).',
        qrAlt: 'QR-код для налаштування автентифікатора',
        manual: 'Або введи ключ вручну:',
        code: 'Код із застосунку',
        confirm: 'Підтвердити',
        cancel: 'Скасувати',
        invalid: 'Невірний код. Спробуй ще раз.',
        error: 'Щось пішло не так. Спробуй ще раз.',
      },
      data: {
        heading: 'Мої дані',
        hint: 'Ти можеш завантажити свої дані або назавжди видалити акаунт.',
        export: 'Завантажити мої дані (JSON)',
        exportError: 'Не вдалося підготувати файл.',
        delete: 'Видалити акаунт',
        deleteWarning: 'Це видалить акаунт і всі твої дані назавжди. Скасувати неможливо.',
        password: 'Підтвердь паролем',
        deleteConfirm: 'Видалити назавжди',
        cancel: 'Скасувати',
        wrongPassword: 'Пароль невірний.',
        deleteError: 'Не вдалося видалити акаунт. Спробуй пізніше.',
      },
    },
    en: {
      title: 'Profile',
      heading: 'My cabinet',
      displayName: 'Name',
      bio: 'About me',
      avatar: 'Emoji avatar',
      timezone: 'Timezone',
      rollover: 'New day starts at (hour)',
      language: 'Language',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark',
      themeSystem: 'System',
      goal: 'Daily XP goal',
      save: 'Save',
      saved: 'Saved ✨',
      saveError: 'Could not save. Please try again.',
      security: 'Security',
      signOut: 'Sign out',
      signOutAll: 'Sign out on all devices',
      photo: {
        label: 'Profile photo',
        upload: 'Upload photo',
        remove: 'Remove photo',
        hint: 'PNG, JPG or WebP, up to 2 MB. Without a photo the emoji avatar is used.',
        badType: 'Only PNG, JPG and WebP are supported.',
        tooBig: 'File is too large. Maximum 2 MB.',
        error: 'Could not update the photo. Please try again.',
      },
      password: {
        heading: 'Change password',
        current: 'Current password',
        next: 'New password',
        confirm: 'Repeat new password',
        hint: 'At least 10 characters.',
        submit: 'Change password',
        done: 'Password changed ✨',
        tooShort: 'Password must be at least 10 characters.',
        same: 'The new password must differ from the current one.',
        mismatch: 'Passwords do not match.',
        wrongCurrent: 'Current password is incorrect.',
        error: 'Could not change the password. Please try again.',
      },
      mfa: {
        heading: 'Two-factor authentication',
        hint: 'An extra code from an authenticator app when you sign in.',
        enabled: 'Two-factor authentication is on ✅',
        enable: 'Turn on',
        disable: 'Turn off',
        scan: 'Scan the QR code in your authenticator app (Google Authenticator, Authy, etc.).',
        qrAlt: 'QR code for setting up the authenticator',
        manual: 'Or enter the key manually:',
        code: 'Code from the app',
        confirm: 'Confirm',
        cancel: 'Cancel',
        invalid: 'Wrong code. Please try again.',
        error: 'Something went wrong. Please try again.',
      },
      data: {
        heading: 'My data',
        hint: 'You can download your data or permanently delete your account.',
        export: 'Download my data (JSON)',
        exportError: 'Could not prepare the file.',
        delete: 'Delete account',
        deleteWarning:
          'This permanently deletes your account and all your data. It cannot be undone.',
        password: 'Confirm with your password',
        deleteConfirm: 'Delete permanently',
        cancel: 'Cancel',
        wrongPassword: 'Incorrect password.',
        deleteError: 'Could not delete the account. Please try later.',
      },
    },
  },
};
