// Builds supabase/migrations/20260929000005_ew_seed.sql from supabase/seed/ew_words_*.txt
// Run: node scripts/gen-ew-seed.mjs   (re-run whenever the word lists change; the migration is idempotent)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

const dir = 'supabase/seed';
const TOPICS = new Set([
  'contract',
  'tort',
  'criminal',
  'procedure',
  'evidence',
  'property',
  'corporate',
  'public',
  'family',
  'academic',
  'general',
]);
const LEVELS = new Set(['B1', 'B2', 'C1']);

const rows = [];
const seen = new Set();
for (const file of readdirSync(dir)
  .filter((f) => /^ew_words_.*\.txt$/.test(f))
  .sort()) {
  readFileSync(`${dir}/${file}`, 'utf8')
    .split(/\r?\n/)
    .forEach((line, i) => {
      if (!line.trim() || line.startsWith('#')) return;
      const f = line.split('|');
      const where = `${file}:${i + 1}`;
      if (f.length !== 8) throw new Error(`${where}: expected 8 fields, got ${f.length}`);
      const [term, pos, ipa, uk, def, example, topics, level] = f.map((s) => s.trim());
      if (seen.has(term.toLowerCase())) throw new Error(`${where}: duplicate term "${term}"`);
      seen.add(term.toLowerCase());
      const tl = topics.split(',');
      if (!tl.every((t) => TOPICS.has(t))) throw new Error(`${where}: bad topic in "${topics}"`);
      if (!LEVELS.has(level)) throw new Error(`${where}: bad level "${level}"`);
      if (!/^\/.+\/$/.test(ipa)) throw new Error(`${where}: bad IPA "${ipa}"`);
      rows.push({ term, pos, ipa, uk, def, example, tl, level });
    });
}
if (rows.length < 300) throw new Error(`Only ${rows.length} words; need at least 300`);

const q = (s) => `'${s.replaceAll("'", "''")}'`;
const values = rows
  .map(
    (r, i) =>
      `  (${q(r.term)}, ${q(r.pos)}, ${q(r.ipa)}, ${q(r.uk)}, ${q(r.def)}, ${q(r.example)}, array[${r.tl.map(q).join(',')}], ${q(r.level)}, ${i + 1})`,
  )
  .join(',\n');

const sql = `-- GENERATED by scripts/gen-ew-seed.mjs from supabase/seed/ew_words_*.txt — do not edit by hand.
-- ${rows.length} shared Legal English + academic words. Idempotent: existing terms are left untouched.
insert into public.ew_words
  (term, pos, ipa, translation_uk, definition_en, example_en, topics, level, sort_order)
values
${values}
on conflict (lower(term)) where owner_id is null do nothing;
`;
writeFileSync('supabase/migrations/20260929000005_ew_seed.sql', sql);
console.log(`Wrote ${rows.length} words`);
